on:
  push:
  pull_request:
    branches: [main]
permissions:
  contents: write
jobs:
  spec:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install shards
        run: shards install
      - name: Run tests
        run: crystal spec

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install shards
        run: shards install
      - name: Run ameba
        run: ./bin/ameba

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v3
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install shards
        run: shards install
      - name: publish API document
        run: crystal doc
      - name: deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4
        with:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_PAT }}
          BRANCH: gh-pages
          FOLDER: docs
          SINGLE_COMMIT: true